# Generated by Django 5.1.2 on 2024-11-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
